load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "traits",
    hdrs = [
        "remove_const_ref.h",
        "with_ref_matching.h",
    ],
    visibility = ["//visibility:public"],
)
