
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "pool",
    srcs = ["pool.hpp"],
    deps = ["@com_github_absl//absl/synchronization"],
    visibility = ["//visibility:public"],
)
