
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "pool",
    srcs = ["pool.h"],
    deps = ["@com_google_absl//absl/synchronization"],
    visibility = ["//visibility:public"],
)
cc_library(
    name = "logger",
    srcs = ["logger.h"],
    deps = ["@com_google_absl//absl/synchronization"],
    visibility = ["//visibility:public"],
)
