name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: jwlawson/actions-setup-bazel@v1.0
      with:
        bazel-version: '2.2.0'
        github-api-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and run tests
      run: bazel test -c opt //...
